const exportObject = Object.freeze({
    SIGN_UP_SOCKET_EVENT:'SIGN_UP',
    GET_TABLE_INFO_SOCKET_EVENT:'GET_TABLE_INFO',
    JOIN_TABLE_SOCKET_EVENT:'JOIN_TABLE',
    ADD_PLAYER_IN_TABLE_ROOM:'JOIN_ROOM',
})

export = exportObject;