const exportObject = Object.freeze({
    SIGN_UP_SOCKET_EVENT:'SIGN_UP',
    GET_TABLE_INFO_SOCKET_EVENT:'GET_TABLE_INFO',
    JOIN_TABLE_SOCKET_EVENT:'JOIN_TABLE',
    ADD_PLAYER_IN_TABLE_ROOM:'JOIN_ROOM',
    GAME_START_SOCKET_EVENT:'GAME_START',
    START_TURN_SOCKET_EVENT:'START_TURN',
    TAKE_TURN_SOCKET_EVENT:'TAKE_TURN',
    SHOW_TAKE_TURN_SOCKET_EVENT:'SHOW_TAKE_TURN',
    WINNER_SOCKET_EVENT:'WINNER',
})

export = exportObject;